application: page-rss
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
- name: lxml
  version: 2.3.5

indexes:
- kind: Feed
  properties:
  - name: user_id
  - name: title
    direction: asc

handlers:
- url: /s
  static_dir: static
- url: /rss/.*
  script: py.main.application
  # no auth, rss readers can read
- url: /
  script: py.main.application
  # no auth, splash page
- url: /admin/.*
  script: py.main.application
  login: admin
- url: /.*
  script: py.main.application
  login: required

